#Header
imc_ros_interface/Header header


# fields
std_msgs/UInt32 path_ref
std_msgs/Float64 start_lat
std_msgs/Float64 start_lon
std_msgs/Float32 start_z
std_msgs/UInt8 start_z_units
std_msgs/Float64 end_lat
std_msgs/Float64 end_lon
std_msgs/Float32 end_z
std_msgs/UInt8 end_z_units
std_msgs/Float32 lradius
std_msgs/UInt8 flags
std_msgs/Float32 x
std_msgs/Float32 y
std_msgs/Float32 z
std_msgs/Float32 vx
std_msgs/Float32 vy
std_msgs/Float32 vz
std_msgs/Float32 course_error
std_msgs/UInt16 eta
